set(PACKAGE_NAME GLEW)

if("${CMAKE_GENERATOR}" MATCHES "MSYS Makefiles")
    SET (GLEW_DIR c:/msys64/mingw64 CACHE PATH "Glew directory")
else()
    SET (GLEW_DIR ${CMAKE_SOURCE_DIR}/3p/glew CACHE PATH "Glew directory")
endif()
add_definitions(-DGLEW_STATIC)

find_path(GLEW_INCLUDE_DIR GL/glew.h 
    HINTS
    ${GLEW_DIR}
    ${VCPKG_DIR}
    $ENV{GLEW_DIR}
    PATH_SUFFIXES include
)
find_library(GLEW_LIBRARY NAMES GLEW glew32s glew glew32
    HINTS
    ${GLEW_DIR}
    ${VCPKG_DIR}
    $ENV{GLEW_DIR}
    PATH_SUFFIXES lib/Release/x64 lib
    )


if(GLEW_FOUND AND NOT TARGET GLEW::GLEW)
  add_library(GLEW::GLEW UNKNOWN IMPORTED)
  set_target_properties(GLEW::GLEW PROPERTIES
    IMPORTED_LOCATION "${GLEW_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${GLEW_INCLUDE_DIRS}")
endif()

#mark_as_advanced(GLEW_INCLUDE_DIR GLEW_LIBRARY)
INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 REQUIRED_VARS GLEW_INCLUDE_DIR GLEW_LIBRARY)